### ISSUE TITLE
Doesn't work on mleap 0.6.0?

### ISSUE THREAD

**Issue by acorso522** [combust/mleap-demo#4]
I'm going through this example and this doesn't seem to work using the current master branch on 0.6.0. There is no mleap.pyspark in master. That said, I also tried using branch feature/scikit-v2 which does have mleap.pyspark, but then when I get to the bottom, it just says 'Pipeline' object has no attribute 'serializeToBundle'. Any ideas on what is going on here?

**Comment by ancasarb** [comment]
@acorso522 are you still having this issue? pyspark support is now available in master branch as well as pypi as a pip package, my suspicion is that you're missing this import statement

```
from mleap.pyspark.spark_support import SimpleSparkSerializer
```

**Comment by ancasarb** [comment]
Closing this, please re-open if it's still an issue. Thank you!
